### ISSUE TITLE
[CRITICAL] Salt shouldn't be accepted in any case

### ISSUE THREAD

**Issue by Suraj-Tiwari** [mdrajibsk8/react-native-payumoney-getway#1]
This package not just handles data unsafely.. also code is just a copy pase from documentation
https://unpkg.com/browse/react-native-payumoney-getway@1.0.5/android/src/main/java/com/payumoneygetwaymoney/PayAction.java

You should not pollute opensource community, also remove your own secret key and salt from testing file.  https://unpkg.com/browse/react-native-payumoney-getway@1.0.5/android/src/main/java/com/payumoneygetwaymoney/Constants.java

**Comment by mdrajibsk8** [comment]
Bro let me tell you something, We created this library because your payumoney library sucks. We tried so many times but your library did not work then we decided to make our own library. You talking about data unsafety and copy from the documentation. So the thing is if I try to create a library then I have to follow the official documentation and data passes safely. So rather than creating an issue in my library why not try to fix your gateway library.

**Comment by Suraj-Tiwari** [comment]
if you think you've better version of it... Then Opensource it why scared to hear truth???... you even don't know difference between salt and merchant id.. instead of critisizing try to do things right way... no ios and crap android code.. etc.. if you don't opensource it.. i'll do it on your behalf as i don't want crap things in community.. i'll let community decide. do whatever you want i don't care about it...
